@host = http://localhost:3000/api

### Obteniendo Todas las Personas
GET {{host}}/requestLocal

### Obteniendo una Persona
GET {{host}}/requestLocal/1

### Creando una Nueva Persona
POST {{host}}/requestLocal
Content-Type: application/json

{
    "pilotName": "Esdras Morales",
    "plate": "O 657BPS",
    "place": "Jalapa",
    "date": "01/01/2022",
    "section": "Jalapa",
    "applicantsName": "Dylan Alexis",
    "position": "Encargado de Area",
    "phoneNumber": 1234567891,
    "observations": "Ninguna",
    "detail":   [
        {
        "dateOf": "2022/01/01", 
        "dateTo": "2022/01/01",
        "schedule": "00:00:00",
        "destiny":"Jalapa",
        "peopleNumber":2,
        "comission":"Local"
        },
        {
        "dateOf": "2022/02/02", 
        "dateTo": "2022/02/02",
        "schedule": "10:10:10",
        "destiny":"Jalapa",
        "peopleNumber":2,
        "comission":"Local"
        }
    ]
}