@host = http://localhost:3000/api

### Obteniendo Todas las Personas
GET {{host}}/requestExterior

### Obteniendo una Persona
GET {{host}}/requestExterior/3

### Creando una Nueva Persona
POST {{host}}/requestExterior
Content-Type: application/json

{
    "requesting_unit": "Comision de Carros",
    "commission_manager": "Ing. Esdras Morales",
    "date_request": "2022/02/02",
    "objective_request": "Ver el estado de los carros",
    "duration_days": "12",
    "phoneNumber": "41806704",
    "observations": "Ninguna",
    "provide_fuel": 0,
    "provide_travel_expenses": 0,
    "plate_vehicle": "O 678PGN",
    "pilot_name": "Dylan Alexis",
    "reason_rejected": "Ninguna",
    "detail":   [
        {
        "number_people": "2",
        "department": "Jalapa",
        "municipality":"Jalapa",
        "village":"Pinula",
        "dateOf": "2022/02/02", 
        "dateTo": "2022/02/02",
        "hour":"10:10:10"
        },
        {
        "number_people": "4",
        "department": "Guatemala",
        "municipality":"Guatemala",
        "village":"Barcenas",
        "dateOf": "2022/01/01", 
        "dateTo": "2022/01/01",
        "hour":"20:20:20"
        },
        {
        "number_people": "2",
        "department": "Jalapa",
        "municipality":"Jalapa",
        "village":"Pinula",
        "dateOf": "2022/02/02", 
        "dateTo": "2022/02/02",
        "hour":"10:10:10"
        },
        {
        "number_people": "4",
        "department": "Guatemala",
        "municipality":"Guatemala",
        "village":"Barcenas",
        "dateOf": "2022/01/01", 
        "dateTo": "2022/01/01",
        "hour":"20:20:20"
        },
        {
        "number_people": "2",
        "department": "Jalapa",
        "municipality":"Jalapa",
        "village":"Pinula",
        "dateOf": "2022/02/02", 
        "dateTo": "2022/02/02",
        "hour":"10:10:10"
        }
    ]
}