@host = http://localhost:3000/api

### Obteniendo Todas las Personas
GET {{host}}/requestLocal

### Obteniendo Todas las Personas
GET {{host}}/requestLocal/onhold

### Obteniendo una Persona
GET {{host}}/requestLocal/15

### Creando una Nueva Persona
POST {{host}}/requestLocal
Content-Type: application/json

{
    "place": "Jalapa",
    "date": "2022/01/01",
    "section": "Jalapa",
    "applicantsName": "Dylan Alexis",
    "position": "Encargado de Area",
    "phoneNumber": 1234567891,
    "observations": "Ninguna",
    "boss": "Dylan",
    "detail":   [
        {
        "dateOf": "2022/01/01", 
        "dateTo": "2022/01/01",
        "schedule": "00:00:00",
        "destiny":"Jalapa",
        "peopleNumber":2,
        "comission":"Local"
        },
        {
        "dateOf": "2022/02/02", 
        "dateTo": "2022/02/02",
        "schedule": "10:10:10",
        "destiny":"Jalapa",
        "peopleNumber":2,
        "comission":"Local"
        }
    ]
}

### Actualizando Solicitud
PUT {{host}}/requestLocal/3
Content-Type: application/json

{
    "pilot_name": "08e25be0-b84e-4bf4-aead-b78990a6072a",
    "plate_vehicle": "1023813281092381",
    "status": 7
}