@host = http://localhost:3000/api/trips

### Obteniendo Todos los viajes exteriores
GET {{host}}/?value=onHold&request=local

### Obteniendo Todos los viajes exteriores
GET {{host}}/exteriorRequest/onhold

### Obteniendo Todos los viajes locales
GET {{host}}/localRequest

### Obteniendo Todos los viajes locales
GET {{host}}/localRequest/onhold

### Creando un Nuevo Viaje Exterior
POST {{host}}/
Content-Type: application/json

{
    "transp_request_exterior": 2,
    "pilot": "b03bee99-4a83-4f4b-a8c0-62a2249fc1fd",
    "vehicle_plate": "1"
}

### Creando un Nuevo Viaje Local
POST {{host}}/
Content-Type: application/json

{
    "transp_request_local": 2,
    "pilot": "08e25be0-b84e-4bf4-aead-b78990a6072a",
    "vehicle_plate": "1023813281092381"
}

### Creando un Nuevo Viaje Local
PUT {{host}}/1
Content-Type: application/json

{
    "status": 11
}
### Obteniendo Todos los viajes locales
GET {{host}}/exitpass/1