@host = http://localhost:3000/api/auth

### OBTENIENDO TODOS LOS USUARIOS
GET {{host}}/users

### OBTENIENDO UN USUARIO
GET {{host}}/user/4df44fd8-e8cc-40f6-b48e-b3cf0612c26f



### Creando un Nuevo Usuario
POST {{host}}/register
Content-Type: application/json

{
    "username": "esdras",
    "password": "1234",
    "rol_id": "4",
    "uuidPerson": "1548e177-2e29-48da-add8-ef1af5c7c2a6"
}


