@host = http://localhost:3000/api

### Obteniendo Todos los Vehiculos
GET {{host}}/vehicles

### Obteniendo un Solo Vehiculo
GET {{host}}/vehicles/1023813281092381

### Creando un Nuevo Vehiculo
POST {{host}}/vehicles
Content-Type: application/json

{
    "vin": "987294729873459",
    "plate": "O0-678PBG",
    "type": "2",
    "brand": "D-MAX",
    "model": 2023,
    "km": 1,
    "gas": "SUPER",
    "status": 1
}

### Modificando un Vehiculo
PUT {{host}}/vehicles/908735saaaaaaaaA
Content-Type: application/json

{
    "plate": "O0-628BBH",
    "type": "1",
    "brand": "MITSUBISHI",
    "model": 2023,
    "km": 1,
    "gas": "SUPER",
    "status": 2
}

### Eliminando un Vehiculo
DELETE {{host}}/vehicles/908735s52415632
Content-Type: application/json