@host = http://localhost:3000/api

###
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
    "username": "DTKingdom",
    "password": "admin234"
}

### Obteniendo Todos los Vehiculos
GET {{host}}/vehicles
Authorization: Bearer {{login.response.body.token}}

### Obteniendo Todos los Vehiculos Activos
GET {{host}}/vehicles/active
Authorization: Bearer {{login.response.body.token}}

### Obteniendo un Solo Vehiculo
GET {{host}}/vehicles/1023813281092381

### Obteniendo un Solo Vehiculo Para el Voucher
GET {{host}}/vehicles/voucher/123141231

### Creando un Nuevo Vehiculo
POST {{host}}/vehicles
Content-Type: application/json

{
    "vin": "987294729873459",
    "plate": "O0-678PBG",
    "type": "2",
    "brand": "D-MAX",
    "model": 2023,
    "km": 1,
    "gas": "SUPER",
    "status": 1,
    "color": 1,
    "cylinders": 4
}

### Modificando un Vehiculo
PUT {{host}}/vehicles/1023813281092381
Content-Type: application/json

{
    "plate": "O0-628BBH",
    "type": "1",
    "brand": "D-MAX",
    "model": 2023,
    "km": 1,
    "gas": "SUPER",
    "status": 2,
    "color": "blanco",
    "cylinders": 4

}

### Eliminando un Vehiculo
DELETE {{host}}/vehicles/908735s52415632
Content-Type: application/json